### ISSUE TITLE
getting mismatch error in 

### ISSUE THREAD

**Issue by AliMedVisionTech** [tiangexiang/BiO-Net#10]
size mistach for post_transform_conv_block.0.weight: copying a param with shape torch.size([32, 96, 3, 3]) from checkpoint, the shape in current model is torch.size([32, 32, 3, 3])

**Comment by tiangexiang** [comment]
Hi, I believe this is because you forgot to set the `--integrate` flag. When iterations=3, the channel number expands three times.

**Comment by AliMedVisionTech** [comment]
thanks for your reply and the problem has been solved. I have one more question is that I am training your model with a new loss function but getting this issue and i don't know how to solve it.

   CORE.train(args)
  File "/home/ali/BioNet_project/pytorch_version/utils.py", line 89, in train
    tot_soft += l.item()
RuntimeError: CUDA error: device-side assert triggered
/opt/conda/conda-bld/pytorch_1614378062065/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [384,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1614378062065/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [385,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1614378062065/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [386,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1614378062065/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [1,0,0], thread: [416,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1614378062065/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [1,0,0], thread: [417,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1614378062065/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [1,0,0], thread: [418,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1614378062065/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [1,0,0], thread: [419,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1614378062065/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [1,0,0], thread: [420,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1614378062065/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [1,0,0], thread: [928,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1614378062065/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [1,0,0], thread: [929,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1614378062065/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [1,0,0], thread: [930,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1614378062065/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [1,0,0], thread: [931,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1614378062065/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [1,0,0], thread: [932,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1614378062065/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [1,0,0], thread: [933,0,0] Assertion `t >= 0 && t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1614378062065/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [1,0,0], thread: [934,0,0] Assertion `t >= 0 && t < n_classes` failed.

**Comment by AliMedVisionTech** [comment]
here is my loss fun.

# def soft_loss(predicted, target, beta=0.95):
#     cross_entropy = F.nll_loss(predicted.log(), target, size_average=False)
#     soft_reed = -predicted * torch.log(predicted + 1e-8)
#     return beta * cross_entropy + (1 -beta) * torch.sum(soft_reed)

**Comment by tiangexiang** [comment]
Hi, this is because either your 'predicted.log()' or 'target' is out of range to the nll_loss function. I suggest changing 'predicted.log()' to 'F.log_softmax(predicted)' and make sure both the input and target meet the interface requirement as specified in https://pytorch.org/docs/stable/nn.functional.html#nll-loss

**Comment by haideralimughal** [comment]
thanks for your reply but i have made changes but still cannot get ride of error 

  File "main.py", line 61, in <module>
    main(args, CORE)
  File "main.py", line 51, in main
    CORE.train(args)
  File "/home/ali/BioNet_project/pytorch_version/utils.py", line 88, in train
    l = criterion(output, y.long())
  File "/home/ali/anaconda3/envs/test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ali/BioNet_project/pytorch_version/loss.py", line 21, in forward
    cross_entropy = F.log_softmax(predicted, target )
  File "/home/ali/anaconda3/envs/test/lib/python3.8/site-packages/torch/nn/functional.py", line 1672, in log_softmax
    ret = input.log_softmax(dim)
TypeError: log_softmax() received an invalid combination of arguments - got (Tensor), but expected one of:
 * (name dim, *, torch.dtype dtype)
 * (int dim, torch.dtype dtype)

**Comment by AliMedVisionTech** [comment]
thanks for your suggestions and I have double-checked on both input and output interface requirements but now facing this weird issue. Any help 

  File "main.py", line 51, in main
    CORE.train(args)
  File "/home/ali/BioNet_project/pytorch_version/utils.py", line 88, in train
    l = criterion(output, y.long())
  File "/home/ali/anaconda3/envs/test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ali/BioNet_project/pytorch_version/loss.py", line 21, in forward
    cross_entropy = F.nll_loss(F.log_softmax(predicted), target, size_average=False)
  File "/home/ali/anaconda3/envs/test/lib/python3.8/site-packages/torch/nn/functional.py", line 2387, in nll_loss
    ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: 1only batches of spatial targets supported (3D tensors) but got targets of size: : [1, 1, 512, 512]

**Comment by tiangexiang** [comment]
Hi, please try to convert your target size from [1, 1, 512, 512] to [1, 512, 512] before passing to F.nll_loss.

**Comment by tiangexiang** [comment]
Closing for now, feel free to reopen if the problem still exists :)
